// Common
export const ADD_ENTITY = "ADD_ENTITY";
export const SET_ENTITY = "SET_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";

// Builder
export const SET_BUILDER_DATA = "SET_BUILDER_DATA";
export const RESET_PIZZA = "RESET_PIZZA";
export const UPDATE_PIZZA_INGREDIENT = "UPDATE_PIZZA_INGREDIENT";
export const UPDATE_READY_PIZZA = "UPDATE_READY_PIZZA";
export const SET_PIZZA_PARAM = "SET_PIZZA_PARAM";

// Cart
export const SET_DELIVERY_PARAM = "SET_DELIVERY_PARAM";
export const RESET_CART = "RESET_CART";
